import { Asset, Evidence, Recommendation, ResourceRequest } from "./types";

export function decide(asset: Asset): Omit<Recommendation, "id" | "createdAt"> {
  const unsafe = asset.condition === "UNSAFE" || /burning|damaged power|smoke|shock/i.test(asset.reportedIssue);
  const evidence: Evidence[] = asset.reportedIssue ? [{ source: "Asset intake record", section: "Reported issue", excerpt: asset.reportedIssue }] : [];
  if (unsafe) return { assetId: asset.id, decision: "RECYCLE", confidence: 0.97, reasons: ["Safety risk is present in the reported condition.", "Continued operation should be prevented until professional inspection."], evidence, alternatives: ["Professional inspection before any disposition"], assumptions: ["No certified safety inspection has been supplied."], humanReviewRequired: true, safetyNote: "Professional inspection required. Do not power on or attempt repair.", approvalStatus: "PENDING" };
  if (asset.condition === "FAIR" && asset.reportedIssue) return { assetId: asset.id, decision: "REPAIR", confidence: 0.84, reasons: ["The asset is in a potentially repairable condition.", "Repair can preserve useful life and avoid immediate procurement.", "The asset has a documented issue that should be assessed by a qualified technician."], evidence, alternatives: ["REFURBISH after inspection", "REPLACE if repair cost is disproportionate"], assumptions: ["Repair parts and qualified service are available.", "No hidden damage has been verified."], humanReviewRequired: true, safetyNote: null, approvalStatus: "PENDING" };
  if (asset.lifecycleStatus === "AVAILABLE" && asset.condition === "GOOD") return { assetId: asset.id, decision: "REDEPLOY", confidence: 0.91, reasons: ["Asset is available and functional.", "Internal reuse should be evaluated before procurement.", "Recorded specifications support institutional matching."], evidence, alternatives: ["REUSE within current department", "REFURBISH if inspection finds wear"], assumptions: ["Inventory status is current.", "Compatibility must be confirmed against the request."], humanReviewRequired: true, safetyNote: null, approvalStatus: "PENDING" };
  if (asset.condition === "POOR") return { assetId: asset.id, decision: "REFURBISH", confidence: 0.68, reasons: ["Condition indicates the asset needs intervention.", "Refurbishment may extend useful service life if economically viable."], evidence, alternatives: ["RECYCLE after professional assessment", "REPLACE if lifecycle cost is excessive"], assumptions: ["No hazardous condition is present."], humanReviewRequired: true, safetyNote: null, approvalStatus: "PENDING" };
  return { assetId: asset.id, decision: "NEEDS_REVIEW", confidence: 0.42, reasons: ["Available evidence is insufficient for a defensible lifecycle decision."], evidence, alternatives: ["Collect maintenance and lifecycle evidence"], assumptions: ["Unknown fields have not been inferred."], humanReviewRequired: true, safetyNote: null, approvalStatus: "PENDING" };
}

export function matchAssets(request: ResourceRequest, assets: Asset[]) {
  return assets.filter(a => a.category === request.category && a.lifecycleStatus === "AVAILABLE" && ["EXCELLENT", "GOOD"].includes(a.condition) && request.specifications.filter(required => !/working/i.test(required)).every(required => a.specs.some(spec => spec.toLowerCase().includes(required.replace("+", "").toLowerCase())))).map(a => ({ assetId: a.id, compatibilityScore: Math.min(0.99, 0.72 + a.specs.length * 0.05), reasons: ["Category matches request.", "Asset is available and in working condition.", `Specifications recorded: ${a.specs.join(", ")}.`], condition: a.condition, location: a.location }));
}
